CREATE TYPE UT_CreateClient AS TABLE  
(  
FirstName VARCHAR(255) NOT NULL,  
LastName VARCHAR(255) NOT NULL,  
PhoneNumber VARCHAR(255) NOT NULL,  
Email VARCHAR(255) NOT NULL,  
Password VARCHAR(255) NOT NULL 
) 